# Generated by Django 4.0.4 on 2022-08-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(max_length=30)),
                ('tag1', models.CharField(max_length=10)),
                ('tag2', models.CharField(max_length=10)),
                ('tag3', models.CharField(max_length=10)),
                ('star', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('spot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alongapp.spot')),
            ],
            bases=('alongapp.spot',),
        ),
    ]
